/* Auto-generated crypto/net stubs for Switch - these are never called */
#include <stddef.h>

void *CryptoNative_Asn1BitStringFree() { return NULL; }
void *CryptoNative_Asn1ObjectFree() { return NULL; }
void *CryptoNative_Asn1OctetStringFree() { return NULL; }
void *CryptoNative_Asn1OctetStringNew() { return NULL; }
void *CryptoNative_Asn1OctetStringSet() { return NULL; }
void *CryptoNative_BigNumDestroy() { return NULL; }
void *CryptoNative_BigNumToBinary() { return NULL; }
void *CryptoNative_BioCtrlPending() { return NULL; }
void *CryptoNative_BioDestroy() { return NULL; }
void *CryptoNative_BioGets() { return NULL; }
void *CryptoNative_BioNewFile() { return NULL; }
void *CryptoNative_BioRead() { return NULL; }
void *CryptoNative_BioSeek() { return NULL; }
void *CryptoNative_BioTell() { return NULL; }
void *CryptoNative_BioWrite() { return NULL; }
void *CryptoNative_CheckX509Hostname() { return NULL; }
void *CryptoNative_CheckX509IpAddress() { return NULL; }
void *CryptoNative_CreateMemoryBio() { return NULL; }
void *CryptoNative_D2IPkcs7Bio() { return NULL; }
void *CryptoNative_DecodeAsn1BitString() { return NULL; }
void *CryptoNative_DecodeExtendedKeyUsage() { return NULL; }
void *CryptoNative_DecodeOcspResponse() { return NULL; }
void *CryptoNative_DecodePkcs7() { return NULL; }
void *CryptoNative_DecodePkcs8PrivateKey() { return NULL; }
void *CryptoNative_DecodeSubjectPublicKeyInfo() { return NULL; }
void *CryptoNative_DecodeX509() { return NULL; }
void *CryptoNative_DecodeX509Crl() { return NULL; }
void *CryptoNative_DsaDestroy() { return NULL; }
void *CryptoNative_DsaGenerateKey() { return NULL; }
void *CryptoNative_DsaKeyCreateByExplicitParameters() { return NULL; }
void *CryptoNative_DsaSizeP() { return NULL; }
void *CryptoNative_EcKeyCreateByExplicitParameters() { return NULL; }
void *CryptoNative_EcKeyCreateByKeyParameters() { return NULL; }
void *CryptoNative_EcKeyCreateByOid() { return NULL; }
void *CryptoNative_EcKeyDestroy() { return NULL; }
void *CryptoNative_EcKeyGenerateKey() { return NULL; }
void *CryptoNative_EcKeyGetCurveName2() { return NULL; }
void *CryptoNative_EcKeyGetSize() { return NULL; }
void *CryptoNative_EncodeAsn1Integer() { return NULL; }
void *CryptoNative_EncodeOcspRequest() { return NULL; }
void *CryptoNative_EncodePkcs7() { return NULL; }
void *CryptoNative_EncodePkcs8PrivateKey() { return NULL; }
void *CryptoNative_EncodeSubjectPublicKeyInfo() { return NULL; }
void *CryptoNative_EncodeX509() { return NULL; }
void *CryptoNative_EncodeX509SubjectPublicKeyInfo() { return NULL; }
void *CryptoNative_EnsureLibSslInitialized() { return NULL; }
void *CryptoNative_ErrClearError() { return NULL; }
void *CryptoNative_ErrErrorStringN() { return NULL; }
void *CryptoNative_ErrGetExceptionError() { return NULL; }
void *CryptoNative_ErrPeekError() { return NULL; }
void *CryptoNative_ErrPeekLastError() { return NULL; }
void *CryptoNative_ErrReasonErrorString() { return NULL; }
void *CryptoNative_EvpAes128Cbc() { return NULL; }
void *CryptoNative_EvpAes128Cfb128() { return NULL; }
void *CryptoNative_EvpAes128Cfb8() { return NULL; }
void *CryptoNative_EvpAes128Ecb() { return NULL; }
void *CryptoNative_EvpAes192Cbc() { return NULL; }
void *CryptoNative_EvpAes192Cfb128() { return NULL; }
void *CryptoNative_EvpAes192Cfb8() { return NULL; }
void *CryptoNative_EvpAes192Ecb() { return NULL; }
void *CryptoNative_EvpAes256Cbc() { return NULL; }
void *CryptoNative_EvpAes256Cfb128() { return NULL; }
void *CryptoNative_EvpAes256Cfb8() { return NULL; }
void *CryptoNative_EvpAes256Ecb() { return NULL; }
void *CryptoNative_EvpCipherCreate2() { return NULL; }
void *CryptoNative_EvpCipherCtxSetPadding() { return NULL; }
void *CryptoNative_EvpCipherDestroy() { return NULL; }
void *CryptoNative_EvpCipherReset() { return NULL; }
void *CryptoNative_EvpCipherUpdate() { return NULL; }
void *CryptoNative_EvpDes3Cbc() { return NULL; }
void *CryptoNative_EvpDes3Cfb64() { return NULL; }
void *CryptoNative_EvpDes3Cfb8() { return NULL; }
void *CryptoNative_EvpDes3Ecb() { return NULL; }
void *CryptoNative_EvpDesCbc() { return NULL; }
void *CryptoNative_EvpDesCfb8() { return NULL; }
void *CryptoNative_EvpDesEcb() { return NULL; }
void *CryptoNative_EvpDigestFinalEx() { return NULL; }
void *CryptoNative_EvpDigestOneShot() { return NULL; }
void *CryptoNative_EvpDigestReset() { return NULL; }
void *CryptoNative_EvpDigestUpdate() { return NULL; }
void *CryptoNative_EvpMd5() { return NULL; }
void *CryptoNative_EvpMdCtxCreate() { return NULL; }
void *CryptoNative_EvpMdCtxDestroy() { return NULL; }
void *CryptoNative_EvpMdSize() { return NULL; }
void *CryptoNative_EvpPKeyBits() { return NULL; }
void *CryptoNative_EvpPKeyDuplicate() { return NULL; }
void *CryptoNative_EvpPKeySize() { return NULL; }
void *CryptoNative_EvpPKeyType() { return NULL; }
void *CryptoNative_EvpPkeyCreate() { return NULL; }
void *CryptoNative_EvpPkeyDestroy() { return NULL; }
void *CryptoNative_EvpPkeyGetDsa() { return NULL; }
void *CryptoNative_EvpPkeyGetEcKey() { return NULL; }
void *CryptoNative_EvpPkeySetDsa() { return NULL; }
void *CryptoNative_EvpPkeySetEcKey() { return NULL; }
void *CryptoNative_EvpRC2Cbc() { return NULL; }
void *CryptoNative_EvpRC2Ecb() { return NULL; }
void *CryptoNative_EvpSha1() { return NULL; }
void *CryptoNative_EvpSha256() { return NULL; }
void *CryptoNative_EvpSha384() { return NULL; }
void *CryptoNative_EvpSha3_256() { return NULL; }
void *CryptoNative_EvpSha3_384() { return NULL; }
void *CryptoNative_EvpSha3_512() { return NULL; }
void *CryptoNative_EvpSha512() { return NULL; }
void *CryptoNative_EvpShake128() { return NULL; }
void *CryptoNative_EvpShake256() { return NULL; }
void *CryptoNative_ExtendedKeyUsageDestroy() { return NULL; }
void *CryptoNative_GetAsn1IntegerDerSize() { return NULL; }
void *CryptoNative_GetAsn1StringBytes() { return NULL; }
void *CryptoNative_GetBigNumBytes() { return NULL; }
void *CryptoNative_GetDsaParameters() { return NULL; }
void *CryptoNative_GetECCurveParameters() { return NULL; }
void *CryptoNative_GetECKeyParameters() { return NULL; }
void *CryptoNative_GetMaxMdSize() { return NULL; }
void *CryptoNative_GetMemoryBioSize() { return NULL; }
void *CryptoNative_GetObjectDefinitionByName() { return NULL; }
void *CryptoNative_GetOcspRequestDerSize() { return NULL; }
void *CryptoNative_GetPkcs7Certificates() { return NULL; }
void *CryptoNative_GetPkcs7DerSize() { return NULL; }
void *CryptoNative_GetPkcs8PrivateKeySize() { return NULL; }
void *CryptoNative_GetRandomBytes() { return NULL; }
void *CryptoNative_GetSubjectPublicKeyInfoSize() { return NULL; }
void *CryptoNative_GetX509CrlNextUpdate() { return NULL; }
void *CryptoNative_GetX509DerSize() { return NULL; }
void *CryptoNative_GetX509EkuField() { return NULL; }
void *CryptoNative_GetX509EkuFieldCount() { return NULL; }
void *CryptoNative_GetX509EvpPublicKey() { return NULL; }
void *CryptoNative_GetX509NameInfo() { return NULL; }
void *CryptoNative_GetX509NameRawBytes() { return NULL; }
void *CryptoNative_GetX509NameStackField() { return NULL; }
void *CryptoNative_GetX509NameStackFieldCount() { return NULL; }
void *CryptoNative_GetX509NotAfter() { return NULL; }
void *CryptoNative_GetX509NotBefore() { return NULL; }
void *CryptoNative_GetX509PublicKeyAlgorithm() { return NULL; }
void *CryptoNative_GetX509PublicKeyBytes() { return NULL; }
void *CryptoNative_GetX509PublicKeyParameterBytes() { return NULL; }
void *CryptoNative_GetX509RootStoreFile() { return NULL; }
void *CryptoNative_GetX509RootStorePath() { return NULL; }
void *CryptoNative_GetX509SignatureAlgorithm() { return NULL; }
void *CryptoNative_GetX509StackField() { return NULL; }
void *CryptoNative_GetX509StackFieldCount() { return NULL; }
void *CryptoNative_GetX509SubjectPublicKeyInfoDerSize() { return NULL; }
void *CryptoNative_GetX509Thumbprint() { return NULL; }
void *CryptoNative_GetX509Version() { return NULL; }
void *CryptoNative_HmacCreate() { return NULL; }
void *CryptoNative_HmacDestroy() { return NULL; }
void *CryptoNative_HmacFinal() { return NULL; }
void *CryptoNative_HmacOneShot() { return NULL; }
void *CryptoNative_HmacReset() { return NULL; }
void *CryptoNative_HmacUpdate() { return NULL; }
void *CryptoNative_IsSslRenegotiatePending() { return NULL; }
void *CryptoNative_IsSslStateOK() { return NULL; }
void *CryptoNative_LookupFriendlyNameByOid() { return NULL; }
void *CryptoNative_NewX509Stack() { return NULL; }
void *CryptoNative_ObjNid2Obj() { return NULL; }
void *CryptoNative_ObjObj2Txt() { return NULL; }
void *CryptoNative_ObjTxt2Nid() { return NULL; }
void *CryptoNative_ObjTxt2Obj() { return NULL; }
void *CryptoNative_OcspRequestDestroy() { return NULL; }
void *CryptoNative_OcspResponseDestroy() { return NULL; }
void *CryptoNative_Pbkdf2() { return NULL; }
void *CryptoNative_PemReadBioPkcs7() { return NULL; }
void *CryptoNative_PemReadBioX509Crl() { return NULL; }
void *CryptoNative_PemReadX509FromBio() { return NULL; }
void *CryptoNative_PemReadX509FromBioAux() { return NULL; }
void *CryptoNative_PemWriteBioX509Crl() { return NULL; }
void *CryptoNative_Pkcs7CreateCertificateCollection() { return NULL; }
void *CryptoNative_Pkcs7Destroy() { return NULL; }
void *CryptoNative_PushX509StackField() { return NULL; }
void *CryptoNative_ReadX509AsDerFromBio() { return NULL; }
void *CryptoNative_RecursiveFreeX509Stack() { return NULL; }
void *CryptoNative_RegisterLegacyAlgorithms() { return NULL; }
void *CryptoNative_RsaGenerateKey() { return NULL; }
void *CryptoNative_SslAddClientCAs() { return NULL; }
void *CryptoNative_SslAddExtraChainCert() { return NULL; }
void *CryptoNative_SslCreate() { return NULL; }
void *CryptoNative_SslCtxAddExtraChainCert() { return NULL; }
void *CryptoNative_SslCtxCheckPrivateKey() { return NULL; }
void *CryptoNative_SslCtxCreate() { return NULL; }
void *CryptoNative_SslCtxDestroy() { return NULL; }
void *CryptoNative_SslCtxGetData() { return NULL; }
void *CryptoNative_SslCtxRemoveSession() { return NULL; }
void *CryptoNative_SslCtxSetAlpnSelectCb() { return NULL; }
void *CryptoNative_SslCtxSetCaching() { return NULL; }
void *CryptoNative_SslCtxSetCiphers() { return NULL; }
void *CryptoNative_SslCtxSetData() { return NULL; }
void *CryptoNative_SslCtxSetDefaultOcspCallback() { return NULL; }
void *CryptoNative_SslCtxSetEncryptionPolicy() { return NULL; }
void *CryptoNative_SslCtxSetKeylogCallback() { return NULL; }
void *CryptoNative_SslCtxSetProtocolOptions() { return NULL; }
void *CryptoNative_SslCtxSetQuietShutdown() { return NULL; }
void *CryptoNative_SslCtxUseCertificate() { return NULL; }
void *CryptoNative_SslCtxUsePrivateKey() { return NULL; }
void *CryptoNative_SslDestroy() { return NULL; }
void *CryptoNative_SslDoHandshake() { return NULL; }
void *CryptoNative_SslGet0AlpnSelected() { return NULL; }
void *CryptoNative_SslGetCertificate() { return NULL; }
void *CryptoNative_SslGetClientCAList() { return NULL; }
void *CryptoNative_SslGetCurrentCipherId() { return NULL; }
void *CryptoNative_SslGetData() { return NULL; }
void *CryptoNative_SslGetFinished() { return NULL; }
void *CryptoNative_SslGetPeerCertChain() { return NULL; }
void *CryptoNative_SslGetPeerCertificate() { return NULL; }
void *CryptoNative_SslGetPeerFinished() { return NULL; }
void *CryptoNative_SslGetServerName() { return NULL; }
void *CryptoNative_SslGetVersion() { return NULL; }
void *CryptoNative_SslRead() { return NULL; }
void *CryptoNative_SslSessionFree() { return NULL; }
void *CryptoNative_SslSessionGetHostname() { return NULL; }
void *CryptoNative_SslSessionReused() { return NULL; }
void *CryptoNative_SslSessionSetData() { return NULL; }
void *CryptoNative_SslSessionSetHostname() { return NULL; }
void *CryptoNative_SslSetAcceptState() { return NULL; }
void *CryptoNative_SslSetAlpnProtos() { return NULL; }
void *CryptoNative_SslSetBio() { return NULL; }
void *CryptoNative_SslSetClientCertCallback() { return NULL; }
void *CryptoNative_SslSetConnectState() { return NULL; }
void *CryptoNative_SslSetData() { return NULL; }
void *CryptoNative_SslSetPostHandshakeAuth() { return NULL; }
void *CryptoNative_SslSetSession() { return NULL; }
void *CryptoNative_SslSetTlsExtHostName() { return NULL; }
void *CryptoNative_SslSetVerifyPeer() { return NULL; }
void *CryptoNative_SslShutdown() { return NULL; }
void *CryptoNative_SslStapleOcsp() { return NULL; }
void *CryptoNative_SslUseCertificate() { return NULL; }
void *CryptoNative_SslUsePrivateKey() { return NULL; }
void *CryptoNative_SslV2_3Method() { return NULL; }
void *CryptoNative_SslWrite() { return NULL; }
void *CryptoNative_Tls13Supported() { return NULL; }
void *CryptoNative_UpRefEvpPkey() { return NULL; }
void *CryptoNative_X509BuildOcspRequest() { return NULL; }
void *CryptoNative_X509ChainBuildOcspRequest() { return NULL; }
void *CryptoNative_X509ChainGetCachedOcspStatus() { return NULL; }
void *CryptoNative_X509ChainHasStapledOcsp() { return NULL; }
void *CryptoNative_X509ChainNew() { return NULL; }
void *CryptoNative_X509ChainVerifyOcsp() { return NULL; }
void *CryptoNative_X509CheckPurpose() { return NULL; }
void *CryptoNative_X509CrlDestroy() { return NULL; }
void *CryptoNative_X509DecodeOcspToExpiration() { return NULL; }
void *CryptoNative_X509Destroy() { return NULL; }
void *CryptoNative_X509ExtensionCreateByObj() { return NULL; }
void *CryptoNative_X509ExtensionDestroy() { return NULL; }
void *CryptoNative_X509ExtensionGetCritical() { return NULL; }
void *CryptoNative_X509ExtensionGetData() { return NULL; }
void *CryptoNative_X509ExtensionGetOid() { return NULL; }
void *CryptoNative_X509FindExtensionData() { return NULL; }
void *CryptoNative_X509GetExt() { return NULL; }
void *CryptoNative_X509GetExtCount() { return NULL; }
void *CryptoNative_X509GetIssuerName() { return NULL; }
void *CryptoNative_X509GetSerialNumber() { return NULL; }
void *CryptoNative_X509GetSubjectName() { return NULL; }
void *CryptoNative_X509IssuerNameHash() { return NULL; }
void *CryptoNative_X509StackAddDirectoryStore() { return NULL; }
void *CryptoNative_X509StackAddMultiple() { return NULL; }
void *CryptoNative_X509StoreAddCrl() { return NULL; }
void *CryptoNative_X509StoreCtxCommitToChain() { return NULL; }
void *CryptoNative_X509StoreCtxCreate() { return NULL; }
void *CryptoNative_X509StoreCtxDestroy() { return NULL; }
void *CryptoNative_X509StoreCtxGetAppData() { return NULL; }
void *CryptoNative_X509StoreCtxGetChain() { return NULL; }
void *CryptoNative_X509StoreCtxGetCurrentCert() { return NULL; }
void *CryptoNative_X509StoreCtxGetError() { return NULL; }
void *CryptoNative_X509StoreCtxGetErrorDepth() { return NULL; }
void *CryptoNative_X509StoreCtxGetSharedUntrusted() { return NULL; }
void *CryptoNative_X509StoreCtxInit() { return NULL; }
void *CryptoNative_X509StoreCtxRebuildChain() { return NULL; }
void *CryptoNative_X509StoreCtxReset() { return NULL; }
void *CryptoNative_X509StoreCtxResetForSignatureError() { return NULL; }
void *CryptoNative_X509StoreCtxSetVerifyCallback() { return NULL; }
void *CryptoNative_X509StoreDestroy() { return NULL; }
void *CryptoNative_X509StoreSetRevocationFlag() { return NULL; }
void *CryptoNative_X509StoreSetVerifyTime() { return NULL; }
void *CryptoNative_X509UpRef() { return NULL; }
void *CryptoNative_X509V3ExtPrint() { return NULL; }
void *CryptoNative_X509VerifyCert() { return NULL; }
void *CryptoNative_X509VerifyCertErrorString() { return NULL; }
void *NetSecurityNative_AcceptSecContext() { return NULL; }
void *NetSecurityNative_DeleteSecContext() { return NULL; }
void *NetSecurityNative_DisplayMajorStatus() { return NULL; }
void *NetSecurityNative_DisplayMinorStatus() { return NULL; }
void *NetSecurityNative_EnsureGssInitialized() { return NULL; }
void *NetSecurityNative_GetMic() { return NULL; }
void *NetSecurityNative_ImportPrincipalName() { return NULL; }
void *NetSecurityNative_ImportUserName() { return NULL; }
void *NetSecurityNative_InitSecContext() { return NULL; }
void *NetSecurityNative_InitSecContextEx() { return NULL; }
void *NetSecurityNative_InitiateCredSpNego() { return NULL; }
void *NetSecurityNative_InitiateCredWithPassword() { return NULL; }
void *NetSecurityNative_IsNtlmInstalled() { return NULL; }
void *NetSecurityNative_ReleaseCred() { return NULL; }
void *NetSecurityNative_ReleaseGssBuffer() { return NULL; }
void *NetSecurityNative_ReleaseName() { return NULL; }
void *NetSecurityNative_VerifyMic() { return NULL; }
#include <unistd.h>
/* pread/pwrite - implement via lseek+read/write+lseek (not atomic but functional) */
#include <unistd.h>
#include <errno.h>
ssize_t pread(int fd, void *buf, size_t count, off_t offset) {
    off_t old = lseek(fd, 0, SEEK_CUR);
    if (old == (off_t)-1) return -1;
    if (lseek(fd, offset, SEEK_SET) == (off_t)-1) return -1;
    ssize_t ret = read(fd, buf, count);
    lseek(fd, old, SEEK_SET);
    return ret;
}
ssize_t pwrite(int fd, const void *buf, size_t count, off_t offset) {
    off_t old = lseek(fd, 0, SEEK_CUR);
    if (old == (off_t)-1) return -1;
    if (lseek(fd, offset, SEEK_SET) == (off_t)-1) return -1;
    ssize_t ret = write(fd, buf, count);
    lseek(fd, old, SEEK_SET);
    return ret;
}
